### PR TITLE
PHPDocs & Reformation & Refactoring

### PR DESCRIPTION
**Pull request by amirkhiz**
- Complete PHPDocs for all API endpoints with doc link
- Add new helper method to check empty parameters
- Reformation

### CODE REVIEW

**Comment by amirkhiz** [comment]
Hi @rytisder,
Could you please test this branch for `Helper::fillParameters()` method uses.
I used this method to check empty parameters in different classes also in `Actions::class`.
At this time I do not have time to have test with real API.
Thanks.

**Comment by rytisder** [comment]
sure, @amirkhiz! Will do it on Monday.

**Comment by rytisder** [comment]
@amirkhiz, I've tested `fillParameters()` and it does work as expected. 

One more thing. Can you rerun PHPDocs on all files?
I've fixed incorrect response types from Helper.php. 
Every API call except `getXML()` should return an array, because default value is 'json' for `parse` function. And if it's JSON type, then it goes through 
`case 'json':
                return json_decode((string)$response->getBody(), true);
` where `true` indicates that it should parse it as a associative array.

**Comment by rytisder** [comment]
Or later I will do it myself on this PR. I have a meeting now, so in a few hours, I will fix it. 🚀

**Comment by rytisder** [comment]
Done, @amirkhiz, please double-check it and we shall merge it.  ⛰️

**Comment by amirkhiz** [comment]
@rytisder Thank you so much for fixing. 👍

**Comment by rytisder** [comment]
No Problem, @amirkhiz! 🥳 

Take a look at this suggestion: https://github.com/amirkhiz/resellerclub-php-api/issues/19

**Comment by amirkhiz** [comment]
I checked that out thanks. good point. :)

**Pull request merged**
